project:
  type: website
  post-render:
    - "cp -rnv static/. _site/"

lang: es

website:
  title: "Jesús Torres"
  site-url: "https://jmtorres.webs.ull.es/"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: https://jesustorres.es/
        icon: box-arrow-up-right
        text: Blog
      - href: ssoo.qmd
        text: SisOp.
      - href: tutorias.qmd
        text: Tutorías
      - href: tfc.qmd
        text: TFG/TFM

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    template-partials:
      - templates/metadata.html
