project:
  type: website
  post-render:
    - "cp -rnv static/. _site/"

website:
  title: "Jesús Torres"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: https://jesustorres.es/
        icon: box-arrow-up-right
        text: Blog
      - href: ssoo.qmd
        text: SisOp.
      - href: tutorias.qmd
        text: Tutorías

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



