project:
  type: website

website:
  title: "Jesús Torres"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: tutorias.qmd
        text: Tuturías

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



