project:
  type: website

website:
  title: "Jesús Torres"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: https://jesustorres.es/
        icon: box-arrow-up-right
        text: Blog
      - href: tutorias.qmd
        text: Tutorías

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



