---
title: "Apuntes de Sistemas Operativos"
---

Las clases de sistemas operativos que imparto se basan en unos apuntes de teor铆a que he ido elaborando a lo largo de los a帽os. Aunque hace tiempo que son p煤blicos, dejo los enlaces por aqu铆, por si pueden resultar interesantes a otras personas.

Los apuntes est谩n hechos con [Asciidoctor](https://asciidoctor.org/) y las fuentes est谩n disponibles en [GitHub](https://github.com/ull-esit-sistemas-operativos/ssoo-apuntes). Desde la secci贸n [*releases*](https://github.com/ull-esit-sistemas-operativos/ssoo-apuntes/releases) de ese mismo repositorio, se puede descargar la 煤ltima versi贸n en PDF. Mientras que la 煤ltima versi贸n en HTML siempre est谩 disponible en:

 [https://ull-esit-sistemas-operativos.github.io/ssoo-apuntes/](https://ull-esit-sistemas-operativos.github.io/ssoo-apuntes/)

Los apuntes cubren los temas:

1. **Introducci贸n a los sistemas operativos**: esta secci贸n proporciona una descripci贸n general de los sistemas operativos, incluyendo su historia, funciones y tipos.
    
2. **Organizaci贸n de los sistemas operativos**: esta secci贸n se centra en la organizaci贸n interna de los sistemas operativos, considerando sus componentes, servicios e interfaces; adem谩s de ofrecer una visi贸n superficial sobre c贸mo funcionan.
    
3. 锔**Gesti贸n de procesos**: esta secci贸n se centra en c贸mo los sistemas operativos gestionan los procesos.
    
4. **Gesti贸n de memoria**: esta secci贸n se centra en c贸mo los sistemas operativos gestionan la memoria principal.
    
5. **Gesti贸n del almacenamiento**: esta secci贸n se centra en como se gestionan los dispositivos de almacenamiento secundario y los sistemas de archivos.
    
A lo largo de los distintos cap铆tulos se hace uso de algunos c贸digos de ejemplo. Estos c贸digos son partes de programas en C o C++ disponibles al completo en el siguiente repositorio:

{{< fa brands github >}} [https://github.com/ull-esit-sistemas-operativos/ssoo-ejemplos](https://github.com/ull-esit-sistemas-operativos/ssoo-ejemplos)
