---
title: Tutorías
---

## Horario de tutorías

Durante el actual curso académico, el horario de tutorías previsto será el siguiente:

* **Lunes**, de 17:00 a 19:00.
* **Martes**, de 17:00 a 19:00.
* **Miércoles**, de 17:00 a 19:00.

Sin embargo, para evitar aglomeraciones y como el horario puede sufrir cambios por distintos motivos, **se recomienda consultar el siguiente 📅calendario** con los horarios actualizados y **coger cita en el hueco deseado**, para confirmar la asistencia:

<!-- Google Calendar Appointment Scheduling begin -->
<iframe src="https://calendar.google.com/calendar/appointments/schedules/AcZssZ1mZRF5_NwlASsNtyeyHikBXGa3LDfa-_jCtbdQQLr7cnYhnlFwyqlGzE8Jo6q4qb8b1eJ39bKb?gv=true" style="border: 0" width="100%" height="600" frameborder="0"></iframe>
<!-- end Google Calendar Appointment Scheduling -->

En caso de tener algún tipo de problema con estos horarios, no dudes en ponerse en 📧[contacto](https://www.ull.es/apps/guias/guias/view_teacher_niu/745/jmtorres/) conmigo para acordar un día y hora alternativos.

## Online / presencial

**Las tutorías pueden ser por videoconferencia**, utilizando Google Meet, **o presenciales**.
En el formulario utilizado para reservar la tutoría se debe indicar la preferencia a este respecto.

## Ubicación

Las tutorías presenciales tendrán lugar en el **despacho P3.08 del edificio de la Escuela Superior de Ingeniería y Tecnología**, ubicado en la última planta del módulo A de dicho edificio.

A continuación se puede ver la ubicación del módulo A de la Escuela Superior de Ingeniería y Tecnología:

<iframe width="800" height="661" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.openstreetmap.org/export/embed.html?bbox=-16.323623657226566%2C28.481687078443027%2C-16.320708096027378%2C28.48455149944618&amp;layer=mapnik&amp;marker=28.48312047743093%2C-16.322167217731476" style="border: 1px solid black"></iframe> 