name: Render and publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
env:
  ULL_WEBS_DEPLOY_URL: https://jmtorres.webs.ull.es/deploy.php
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render website
        uses: quarto-dev/quarto-actions/render@v2
      - name: Publish to GitHub PAges
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          clean: true
      - name: Publish to ULL Webpages
        run: curl -X GET "${{ env.ULL_WEBS_DEPLOY_URL }}?sat=${{ secrets.DEPLOY_TOKEN }}"